# Site settings
name: Lucas The Nomad
title: Lucas The Nomad
author:  Lucas
email: lparry@gmail.com
description: "Lucas The Nomad"
baseurl: ""
url: "http://www.lucasthenomad.com"
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
permalinks: pretty
source:  source
destination: public
plugins: plugins
exclude: [vendor, .git]

date_format: "ordinal"

paginate:      10          # Posts per page on the blog index
paginate_path: "/blog/page/:num"
excerpt_separator: "<!-- more -->"

sass:
    sass_dir: _sass
    style: :compressed

